server:
  port: 12020
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bieshengping/tuling-springcloud-config-server.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://biege:123@127.0.0.1:8761/eureka,http://biege:123@127.0.0.1:8762/eureka,http://biege:123@127.0.0.1:8763/eureka

#####################################
通过eureka实现 config-server统一配置中心服务端高可用
测试过程:
    启动三个 10-09-ms-config-server-eureka ,端口分别为 12000  12010  12020
    都分别注册进 eureka中.

