server:
  port: 12000
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bieshengping/tuling-springcloud-config-server.git      # 配置Git仓库的地址
          search-paths: encryption
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码

