server:
  port: 8010
spring:
  application:
    name: microservice-consumer-order
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://biege:123@127.0.0.1:8761/eureka,http://biege:123@127.0.0.1:8762/eureka,http://biege:123@127.0.0.1:8763/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3  # 3秒一次心跳,开发阶段,服务提供方修改此值
    lease-expiration-duration-in-seconds: 5  # 5秒即过期,开发阶段,服务提供方修改此值