spring:
  application:
    name: microservice-eureka-server-ha
  security:
    user:
      name: biege
      password: 123
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000

---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka8761.com                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://biege:123@eureka8762.com:8762/eureka,http://biege:123@eureka8763.com:8763/eureka      # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka8762.com
  client:
    serviceUrl:
      defaultZone: http://biege:123@eureka8761.com:8761/eureka,http://biege:123@eureka8763.com:8763/eureka

---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: eureka8763.com
  client:
    serviceUrl:
      defaultZone: http://biege:123@eureka8761.com:8761/eureka,http://biege:123@eureka8762.com:8762/eureka